from node

copy package.json package.json
copy package-lock.json package-lock.json
copy routes routes
copy middleware middleware
copy model model
copy db db
copy controllers controllers
copy app.js app.js

run npm install

ENTRYPOINT ["node","app.js"]